name: Deploy Next.js App

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: "Commit hash to deploy"
        required: true
      deployment_name:
        description: "Deployment name (for tracking)"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the specified commit
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_hash }}

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Transfer full project to SSH server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key

          # Sync the entire project directory to the remote server
          rsync -avz --exclude="node_modules" --exclude=".git" \
            -e "ssh -i private_key -o StrictHostKeyChecking=no" \
            . $SSH_USER@$SSH_HOST:/home/ubuntu/portfolio/

          rm -f private_key

      - name: Set up server, install Node.js, and start app
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key

          ssh -i private_key -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            # Update package lists
            sudo apt update -y

            # Install Node.js and npm (if not installed)
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt install -y nodejs
            fi

            # Ensure portfolio directory exists
            mkdir -p /home/ubuntu/portfolio
            cd /home/ubuntu/portfolio

            # Install dependencies (without devDependencies)
            npm install --omit=dev

            # Install PM2 globally
            sudo npm install -g pm2

            # Ensure PM2 is in PATH
            export PATH="$PATH:$(npm root -g)"

            # Stop any running instance of the app
            pm2 delete portfolio || true

            # Start the Next.js app with PM2
            pm2 start "npm run start" --name "portfolio"

            # Save PM2 process list
            pm2 save
          EOF

          rm -f private_key
