name: Deploy Next.js App

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: "Commit hash to deploy"
        required: true
      deployment_name:
        description: "Deployment name (for tracking)"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the specified commit
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_hash }}

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Transfer build files to SSH server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" .next $SSH_USER@$SSH_HOST:/home/ubuntu/portfolio/
          rm -f private_key

      - name: Install Node.js, PM2, and dependencies on server & restart app
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            # Update packages
            sudo apt update -y
            
            # Install Node.js & npm if not installed
            if ! command -v node &> /dev/null
            then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt install -y nodejs
            fi

            # Install PM2 globally if not installed
            if ! command -v pm2 &> /dev/null
            then
              npm install -g pm2
              pm2 startup
            fi

            # Navigate to deployment directory
            cd /home/ubuntu/portfolio

            # Install production dependencies
            npm install --omit=dev

            # Restart the Next.js app using PM2
            pm2 delete portfolio || true
            pm2 start npm --name "portfolio" -- start
            pm2 save
          EOF
          rm -f private_key
